### ISSUE TITLE
Won't work in Firefox

### ISSUE THREAD

**Issue by MarcGamesons** [MarcGamesons/twitch-userscript-use-chitchat#1]
Firefox doesn't allow the unsecure ws:// protocol in secure https:// protocol enabled webpages. The server owners (ChitChat and Twitch) would have to upgrade to the secure wss:// protocol.

A user on stackoverflow suggests to disable a setting in Firefox as a workaround.

~~"Going to firefox's about:config and toggling network.websocket.allowInsecureFromHTTPS will get rid of the SecurityError." - source: https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue~~ This doesn't work but you can read more about the error on stackoverflow.

I am sorry but for now I am not able to fix this issue.

**Comment by azizLIGHT** [comment]
Not sure what version of firefox you used but I am on Firefox 64 and use chitchat just fine on twitch

**Comment by MarcGamesons** [comment]
It was not working at the time I created the issue and I actually never checked if it was working in newer versions. Thanks for you feedback. This issue is now closed.
