### ISSUE TITLE
[REQUEST] Bookmarklet version

### ISSUE THREAD

**Issue by omen124** [MarcGamesons/twitch-userscript-use-chitchat#26]
Would it be possible to turn your userscript into a bookmarklet that can be added to the bookmark bar allowing you to enable it when you wanted it?
It also makes it one less thing required to be installed (mod for the browser).

**Comment by MarcGamesons** [comment]
I don't know anything about developing bookmarklets. Right now the JavaScript of the UserScript is loading on DOM Ready and observing mutations to replace the Chat with an embed. Let me try to come up with a solution over the next few days, it might be easier then I think. I am already thinking about a solution that might work for a bookmarklet.

**Comment by MarcGamesons** [comment]
Done. [Replace Chat with ChitChat](javascript:(function()%7B%2F%2F%20Get%20the%20container%20that%20contains%20the%20chat%20messages.%0A%20%20%20%20%20%20%20%20const%20chatContainer%20%3D%20document.querySelector(%22.chat-list--default%22)%3B%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Delete%20all%20child%20nodes.%0A%20%20%20%20%20%20%20%20while%20(chatContainer.firstChild)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20chatContainer.removeChild(chatContainer.firstChild)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Create%20an%20iframe%20and%20load%20ChitChat%20into%20it%0A%20%20%20%20%20%20%20%20const%20chatFrame%20%3D%20document.createElement(%22iframe%22)%3B%0A%20%20%20%20%20%20%20%20const%20casterURL%20%3D%20window.location.pathname.split('%2F')%3B%0A%20%20%20%20%20%20%20%20%2F%2F%20chatFrame.id%20%3D%20%22ChitChatFrame%22%3B%0A%20%20%20%20%20%20%20%20chatFrame.setAttribute(%22src%22%2C%20%22https%3A%2F%2Fchitchat.ma.pe%2F%22%20%2B%20casterURL%5B1%5D)%3B%0A%20%20%20%20%20%20%20%20chatFrame.style.width%20%3D%20%22100%25%22%3B%0A%20%20%20%20%20%20%20%20chatFrame.style.height%20%3D%20%2299%25%22%3B%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Append%20the%20iframe%20to%20the%20container%20that%20contains%20the%20chat%20messages.%0A%20%20%20%20%20%20%20%20chatContainer.appendChild(chatFrame)%3B%7D)()%3B)

**Comment by MarcGamesons** [comment]
Wait I can't link that here let me modify the readme.
