### ISSUE TITLE
[BUG] Works fine except in Popout Chat

### ISSUE THREAD

**Issue by BobDaBilda** [MarcGamesons/twitch-userscript-use-chitchat#29]
**Describe the bug**
The script works perfectly in most normal chats. But when you pop out a chat, the link goes from "twitch.tv/[channel name]" to "twitch.tv/popout/[channel name]/chat?popout="

**To Reproduce**
1. Go to any channel.
2. Click on the settings menu
3. Click popout chat
4. Script tries to join channel "Popout" through chitchat.

**Expected behavior**
[channel name] is joined instead of "popout"

**Screenshots**
https://i.imgur.com/sWPq1zA.png

**Desktop (please complete the following information):**
 - Browser [Edge Chromium]
 - Version [Version 99.0.1150.46 (Official build) (64-bit)]

**Comment by MarcGamesons** [comment]
Just to make sure I understand you correctly, you are first running the script on a channel and then clicking on popout chat, right? And the browser window that contains the popout isn't using the script (chit chat) anymore.

**Comment by BobDaBilda** [comment]
Usually, yes. But sometimes I go to a particular chat's popout link after having visited it, to be in chat without being on the stream. But yes, 9 times out of 10, I'm just pressing the popout button. 

Edit: I misread the end of your question / statement. The script is still working, and I get chit chat, but in the wrong channel. 

For example: If I'm trying to popout the chat of the channel "twitch.tv/twitch", it becomes "twitch.tv/popout" 's chat, instead of "/twitch". 

Edit2: If you join an embedded chat, you join the channel "embed" in the same way as joining "popout" above.
