### ISSUE TITLE
Doesn't work on multitwitch

### ISSUE THREAD

**Issue by azizLIGHT** [MarcGamesons/twitch-userscript-use-chitchat#3]
Try going to http://www.multitwitch.tv/forsen/sweet_anita . Chat gets loaded and then switches to chitchat but chitchat is empty and it says it has "Joined #embed". This happens for every stream you loaded in multitwitch

Similarly, multistre.am also behaves the same way. Example link: https://multistre.am/forsen/sweet_anita/layout3/

**Comment by MarcGamesons** [comment]
I will try to come up with a solution for this but I can't promise anything.

**Comment by MarcGamesons** [comment]
This issue will be closed, because it is really old. I never found a solution at that point in time, moved on to other things and simply forgot about this. If this still should be a feature people wish for, then feel free to open a new issue.
