### ISSUE TITLE
Spam Reason taking up space even when disabled.

### ISSUE THREAD

**Issue by azizLIGHT** [MarcGamesons/twitch-userscript-use-chitchat#4]
There seems to be an invisible barrier at the extreme right of every chat line that is blocking chat from reaching all the way to the end of the line. This happens even though I have "Hide spam reason" enabled. This messes up formatting and copypasta alignment, and just makes the chit side of chitchat unnecessarily skinny: 
![image](https://user-images.githubusercontent.com/8013867/50114077-a48e4e80-0211-11e9-802a-005bb796be3c.png)

I am on Firefox 64 with Tampermonkey 4.8.5847 with your userscript latest version

**Comment by MarcGamesons** [comment]
There is nothing I can do about this see #5.

"You would have to contact the creator of ChitChat (https://github.com/mape) and ask if they can do something about that."
