### ISSUE TITLE
@mentions messages are colored red

### ISSUE THREAD

**Issue by azizLIGHT** [MarcGamesons/twitch-userscript-use-chitchat#5]
I think chitchat was designed for streamers, not viewers. So, opening a stream (lets say forsen) with chitchat enabled shows red colored messages for lines that mention @forsen. This would make sense if I was forsen, but I am a viewer and the red colored messages should be for lines that mention @me not the streamer. Perhaps there should be some kind of choice.
Example:
![image](https://user-images.githubusercontent.com/8013867/50114711-38ace580-0213-11e9-90c7-c744a7c56847.png)

**Comment by MarcGamesons** [comment]
This is intended behaviour of ChitChat, there is nothing I can do about that. I only embed ChitChat on Twitch via userscript.

You would have to contact the creator of ChitChat (https://github.com/mape) and ask if they can do something about that.
