### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by toppits** [MarcGamesons/twitch-userscript-use-chitchat#6]
All i get is a purple/black gradient frame. Turned all script blockers off but nothing.

ps: im on chrome win64

**Comment by MarcGamesons** [comment]
It does still work for me. Chrome version during testing was: 80.0.3987.106 (64-Bit). No extensions used except Tampermonkey BETA 4.10.6109  and the script.

Does it work on the website for you? [https://chitchat.ma.pe/](https://chitchat.ma.pe/)

Are you blocking some third party cookies that are needed? You can enable/disable certain things regarding tracking and cookies in your browser without the need of addons/extensions from the chrome webstore. Maybe you have something blocked in the default Chrome settings?

**Comment by toppits** [comment]
Hmm, ok. Website works fine. I have 3rd party blocked in chrome settings, so i'll have to see whats up.

Just realized though, chitchat can only be used on live anyway so its not a big deal. I'll open it separately then. 

Thanks for the response and thanks for making the script.
#
E: enabling 3rd party fixed it

**Comment by MarcGamesons** [comment]
This issue will be closed, because of inactivity. If there still should be something wrong you can always create a new issue.
